Revert "msm: kgsl: Add gpu_frequency tracepoint to power trace system"
undefined reference to `__tracepoint_gpu_frequency'? No more! This reverts commit 1b6f6cfd40bd2df26f4c5b939b33dddb5c09ceee.

Signed-off-by: Udit Karode <udit.karode@gmail.com>
Signed-off-by: Shivam Kumar <kumar.shivam.jarvis@gmail.com>